server: 
    # 服务端口
    port: @server.port@
    # 服务路径
    contextPath: @server.contextpath@

spring:
    # 服务名称
    application:
        name: resultEntry
    # 服务当前使用的profile
    profiles: 
        active: @spring.profiles.active@
    jackson:
        # json中日期是否用timestamps格式交互
        serialization.write-dates-as-timestamps: true
        # json中遇到无效变量是否报错
        deserialization.FAIL_ON_UNKNOWN_PROPERTIES: off
# LOG相关设置
logging:
    path: @logging.path@
